// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_parallax(k, g, a) {
    var c = jQuery;
    var f = c(this);
    var d = a.find(".ws_list");
    var b = k.parallax || 0.25;
    var e = c("<div>").css({
        position: "absolute",
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
        overflow: "hidden"
    }).addClass("ws_effect ws_parallax").appendTo(a);

    function j(l) {
        return Math.round(l * 1000) / 1000
    }
    var i = c("<div>").css({
        position: "absolute",
        left: 0,
        top: 0,
        overflow: "hidden",
        width: "100%",
        height: "100%",
        transform: "translate3d(0,0,0)"
    }).appendTo(e);
    var h = i.clone().appendTo(e);
    this.go = function(l, r, p) {
        var s = c(g.get(r));
        s = {
            width: s.width(),
            height: s.height(),
            marginTop: s.css("marginTop"),
            marginLeft: s.css("marginLeft")
        };
        p = p ? 1 : -1;
        var n = c(g.get(r)).clone().css(s).appendTo(i);
        var o = c(g.get(l)).clone().css(s).appendTo(h);
        var m = a.width() || k.width;
        var q = a.height() || k.height;
        d.hide();
        wowAnimate(function(v) {
            v = c.easing.swing(v);
            var x = j(p * v * m),
                u = j(p * (-m + v * m)),
                t = j(-p * m * b * v),
                w = j(p * m * b * (1 - v));
            if (k.support.transform) {
                i.css("transform", "translate3d(" + x + "px,0,0)");
                n.css("transform", "translate3d(" + t + "px,0,0)");
                h.css("transform", "translate3d(" + u + "px,0,0)");
                o.css("transform", "translate3d(" + w + "px,0,0)")
            } else {
                i.css("left", x);
                n.css("margin-left", t);
                h.css("left", u);
                o.css("margin-left", w)
            }
        }, 0, 1, k.duration, function() {
            e.hide();
            n.remove();
            o.remove();
            f.trigger("effectEnd")
        })
    }
}; // -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery.extend(jQuery.easing, {
    easeInBack: function(e, f, a, i, h, g) {
        if (g == undefined) {
            g = 1.70158
        }
        return i * (f /= h) * f * ((g + 1) * f - g) + a
    },
    easeOutBack: function(e, f, a, i, h, g) {
        if (g == undefined) {
            g = 1.70158
        }
        return i * ((f = f / h - 1) * f * ((g + 1) * f + g) + 1) + a
    },
    easeInBackQ: function(e, f, a, j, i, g) {
        var h = (f /= i) * f;
        return a + j * h * (4 * f * h - 8 * h + 8 * f - 3)
    },
    easeOutBackQ: function(e, f, a, j, i, g) {
        var h = (f /= i) * f;
        return a + j * (4 * h * f * h - 12 * h * h + 16 * h * f - 13 * h + 6 * f)
    },
    easeInBackQ2: function(e, f, a, j, i, g) {
        var h = (f /= i) * f;
        return a + j * h * (1.5 * f * h - 2.5 * h + 5 * f - 3)
    },
    easeOutBackQ2: function(e, f, a, j, i, g) {
        var h = (f /= i) * f;
        return a + j * (1.5 * h * f * h - 5 * h * h + 10 * h * f - 12 * h + 6.5 * f)
    }
});

function ws_brick(f, s, g) {
    var h = jQuery,
        n = h(this),
        a = f.cols || 4,
        r = f.rows || 3,
        H = 2.5,
        c = 2,
        v = f.perspective || 2000,
        u = g.find(".ws_list"),
        G = [],
        b = 30,
        x = {},
        o = h("<div>").addClass("ws_effect ws_brick").appendTo(g),
        q = f.support.transform && f.support.transition && f.support.perspective,
        p = /Safari/.test(navigator.userAgent) && !/Chrome/.test(navigator.userAgent),
        m = /Firefox/.test(navigator.userAgent);
    var y = [{
        zIndex: 0,
        rotateX: 360,
        rotateZ: -360,
        rotateY: 180,
        halfScale: 0.5,
        halfLeft: 0.7,
        halfTop: 0.7,
        delay: 0.36
    }, {
        zIndex: 1,
        rotateX: -360,
        rotateZ: 360,
        rotateY: 180,
        halfScale: 0.5,
        halfLeft: 0.2,
        halfTop: 0.4,
        delay: 0.81
    }, {
        zIndex: 1,
        rotateX: 360,
        rotateZ: -360,
        rotateY: -180,
        halfScale: 0.5,
        halfLeft: -0.2,
        halfTop: 0.4,
        delay: 0.45
    }, {
        zIndex: 0,
        rotateX: -360,
        rotateZ: 360,
        rotateY: -180,
        halfScale: 0.5,
        halfLeft: -0.7,
        halfTop: 0.7,
        delay: 0.63
    }, {
        zIndex: 1,
        rotateX: -360,
        rotateZ: 360,
        rotateY: -180,
        halfScale: 0.5,
        halfLeft: 0.7,
        halfTop: 0,
        delay: 0.54
    }, {
        zIndex: 2,
        rotateX: 360,
        rotateZ: -360,
        rotateY: 180,
        halfScale: 0.5,
        halfLeft: 0.2,
        halfTop: 0,
        delay: 0.38
    }, {
        zIndex: 2,
        rotateX: 360,
        rotateZ: -360,
        rotateY: -180,
        halfScale: 0.5,
        halfLeft: -0.2,
        halfTop: 0,
        delay: 0
    }, {
        zIndex: 1,
        rotateX: -360,
        rotateZ: 360,
        rotateY: 180,
        halfScale: 0.5,
        halfLeft: -0.7,
        halfTop: 0,
        delay: 0.72
    }, {
        zIndex: 0,
        rotateX: -360,
        rotateZ: 360,
        rotateY: 180,
        halfScale: 0.5,
        halfLeft: 0.7,
        halfTop: -0.7,
        delay: 1
    }, {
        zIndex: 1,
        rotateX: -360,
        rotateZ: 360,
        rotateY: -180,
        halfScale: 0.5,
        halfLeft: 0.2,
        halfTop: -0.4,
        delay: 0.7
    }, {
        zIndex: 1,
        rotateX: 360,
        rotateZ: -360,
        rotateY: 180,
        halfScale: 0.5,
        halfLeft: -0.2,
        halfTop: -0.4,
        delay: 0.57
    }, {
        zIndex: 0,
        rotateX: 360,
        rotateZ: -360,
        rotateY: -180,
        halfScale: 0.5,
        halfLeft: -0.7,
        halfTop: -0.7,
        delay: 0.9
    }, ];
    o.css({
        position: "absolute",
        top: 0,
        left: 0,
        width: g.width(),
        height: g.height(),
        transform: "translate3d(0,0,0)",
        transformOrigin: (f.width / 2) + "px " + (f.height / 2) + "px 0",
        perspective: v
    }).hide();
    for (var l = 0; l < a * r; l++) {
        var B = l % a,
            A = Math.floor(l / a);
        var E = h("<div>").css({
                position: "absolute",
                left: 100 * B / a + "%",
                top: 100 * A / r + "%",
                outline: "1px solid transparent",
                transformStyle: (p || m) ? "flat" : "preserve-3d",
                zIndex: y[l].zIndex,
                overflow: q ? "visible" : "hidden"
            }).appendTo(o),
            z = h("<div>").css({
                transform: "scale(1) rotateX(0) rotateY(0) translate3d(0,0,0)",
                outline: "1px solid transparent",
                transformStyle: "preserve-3d"
            }).appendTo(E),
            w = h("<div>").addClass("ws_front_image").appendTo(z),
            D = q ? h("<div>").addClass("ws_back_image").appendTo(z) : 0;
        w.css({
            position: "absolute",
            width: "100%",
            height: "100%",
            overflow: "hidden",
            backfaceVisibility: "hidden",
            transform: "translate3d(0,0,0)"
        }).append(h("<img>").css({
            left: -B * 100 + "%",
            top: -A * 100 + "%",
            position: "absolute",
            outline: "1px solid transparent"
        }));
        if (q) {
            D.css({
                position: "absolute",
                width: "100%",
                height: "100%",
                overflow: "hidden",
                backfaceVisibility: "hidden",
                transform: "rotateY(180deg) translate3d(0,0," + b + "px)"
            }).append(h("<img>").css({
                left: -B * 100 + "%",
                top: -A * 100 + "%",
                position: "absolute",
                outline: "1px solid transparent"
            }))
        }
        var t = {
            position: "absolute",
            outline: "1px solid transparent"
        };
        G[l] = {
            part: z,
            front: w,
            back: D,
            wrapper: E,
            leftEdge: q ? h("<div>").addClass("ws_left_edge").css(t).appendTo(z) : 0,
            rightEdge: q ? h("<div>").addClass("ws_right_edge").css(t).appendTo(z) : 0,
            topEdge: q ? h("<div>").addClass("ws_top_edge").css(t).appendTo(z) : 0,
            bottomEdge: q ? h("<div>").addClass("ws_bottom_edge").css(t).appendTo(z) : 0
        }
    }

    function C(N) {
        var J = {},
            L = s.get(N),
            O = f.width / a,
            P = f.height / r;
        for (var K = 0; K < a * r; K++) {
            var N = K % a,
                M = Math.floor(K / a);
            J[K] = F(L, {
                x: N * O,
                y: M * P,
                w: O,
                h: P
            })
        }
        return J
    }

    function I(J, M, j, K, L) {
        for (var i in M) {
            if (typeof G[i] !== "function") {
                M[i].topEdge.css({
                    width: K,
                    height: J,
                    background: j[i],
                    transform: "rotateX(90deg) translate3d(0,-" + J / 2 + "px," + J / 2 + "px)"
                });
                M[i].bottomEdge.css({
                    width: K,
                    height: J,
                    background: j[i],
                    transform: "rotateX(90deg) translate3d(0,-" + J / 2 + "px," + (-L + J / 2) + "px)"
                });
                M[i].leftEdge.css({
                    width: J,
                    height: L,
                    background: j[i],
                    transform: "rotateY(90deg) translate3d(" + J / 2 + "px,0,-" + J / 2 + "px)"
                });
                M[i].rightEdge.css({
                    width: J,
                    height: L,
                    background: j[i],
                    transform: "rotateY(90deg) translate3d(" + J / 2 + "px,0," + (K - J / 2) + "px)"
                })
            }
        }
    }

    function e(J, K) {
        var i = 0;
        for (var j in J) {
            if (typeof J[j] !== "function") {
                (function(L, M) {
                    wowAnimate(function(O) {
                        var U, S, T, R = "",
                            N = {};
                        if (O <= 0.5) {
                            U = h.easing.easeInBack(1, O * 2, 0, 1, 1, 1).toFixed(3);
                            S = h.easing.easeInBackQ(1, O * 2, 0, 1, 1, 1).toFixed(3);
                            T = h.easing.easeInBackQ2(1, O * 2, 0, 1, 1, 1).toFixed(3);
                            M[L].back.css("backfaceVisibility", "hidden")
                        } else {
                            U = h.easing.easeOutBack(1, (O - 0.5) * 2, 0, 1, 1, 1).toFixed(3);
                            S = h.easing.easeOutBackQ(1, (O - 0.5) * 2, 0, 1, 1, 1).toFixed(3);
                            T = h.easing.easeOutBackQ2(1, (O - 0.5) * 2, 0, 1, 1, 1).toFixed(3);
                            M[L].back.css("backfaceVisibility", "visible")
                        }
                        for (var P in M[L].animate[O <= 0.5 ? "half" : "end"]) {
                            var V = M[L].animate[O <= 0.5 ? "begin" : "half"][P] || 0,
                                Q = M[L].animate[O <= 0.5 ? "half" : "end"][P] || 0;
                            if (typeof Q !== "object") {
                                if (P === "scale" || P === "rotateX" || P === "rotateY") {
                                    Q = V + (Q - V) * S
                                } else {
                                    if (P === "left" || P === "top") {
                                        Q = V + (Q - V) * T
                                    } else {
                                        Q = V + (Q - V) * U
                                    }
                                }
                            }
                            if (P === "rotateX" || P === "rotateY" || P === "rotateZ") {
                                R += P + "(" + Q + "deg) "
                            } else {
                                if (P === "scale") {
                                    R += P + "(" + Q + ") "
                                } else {
                                    if (P === "translate3d") {
                                        R += P + "(" + (V[0] + (Q[0] - V[0]) * U).toFixed(3) + "px," + (V[1] + (Q[1] - V[1]) * U).toFixed(3) + "px," + (V[2] + (Q[2] - V[2]) * U).toFixed(3) + "px) "
                                    } else {
                                        N[P] = Q
                                    }
                                }
                            }
                        }
                        M[L].wrapper.css({
                            transform: "translate3d(" + (N.left ? N.left : 0).toFixed(3) + "px," + (N.top ? N.top : 0).toFixed(3) + "px,0)"
                        });
                        delete N.left;
                        delete N.top;
                        if (R) {
                            N.transform = R
                        }
                        M[L].part.css(N)
                    }, 0, 1, M[L].animate.duration, M[L].animate.delay, function() {
                        i++;
                        if (i == M.length && K) {
                            K()
                        }
                    })
                }(j, J))
            }
        }
    }

    function k(aa, M, N, P) {
        var X = g.width(),
            W = g.height(),
            V = X / a,
            U = W / r,
            L = (f.duration * 0.4) > 1000 ? 1000 : (f.duration * 0.4),
            K = f.duration * 0.6,
            Q = [0, 0];
        I(b, aa, x[M], V, U);
        o.css({
            transformOrigin: (X / 2) + "px " + (W / 2) + "px 0",
            width: X,
            height: W
        });
        for (var S in aa) {
            if (typeof aa[S] !== "function") {
                var J = y[S].delay * L;
                if (Q[1] <= J) {
                    Q[0] = S;
                    Q[1] = J
                }
                aa[S].part[0].ws_delay = [J, 0]
            }
        }
        aa[Q[0]].part[0].ws_delay[1] = 1;
        for (var S in aa) {
            if (typeof aa[S] !== "function") {
                var R = aa[S],
                    Z = S % a,
                    Y = Math.floor(S / a),
                    T = X * Z / a,
                    O = W * Y / r;
                R.animate = {
                    delay: R.part[0].ws_delay[0],
                    duration: K,
                    begin: {
                        left: 0,
                        top: 0,
                        width: V,
                        height: U,
                        scale: 1,
                        rotateX: 0,
                        rotateY: 0,
                        translate3d: [0, 0, p ? b : 0]
                    },
                    half: {
                        left: y[S].halfLeft * V,
                        top: y[S].halfTop * U,
                        scale: y[S].halfScale,
                        rotateX: y[S].rotateX / 2,
                        rotateY: y[S].rotateY / 2,
                        translate3d: [0, 0, (p ? 1 : 0.5) * b]
                    },
                    end: {
                        left: 0,
                        top: 0,
                        scale: 1,
                        rotateX: y[S].rotateX,
                        rotateY: y[S].rotateY,
                        translate3d: [0, 0, b]
                    }
                };
                R.front.find("img").css(N);
                R.back.css("backfaceVisibility", "hidden").find("img").css(N);
                R.part.css({
                    width: R.animate.begin.width,
                    height: R.animate.begin.height,
                    left: R.animate.begin.left,
                    top: R.animate.begin.top
                })
            }
        }
        e(aa, P)
    }
    var d;
    this.go = function(X, M) {
        if (d) {
            return M
        }
        o.show();
        var K = h(s.get(M));
        K = {
            width: K.width(),
            height: K.height(),
            marginTop: parseFloat(K.css("marginTop")),
            marginLeft: parseFloat(K.css("marginLeft"))
        };
        if (q) {
            G[0].front.find("img").on("load", function() {
                u.hide()
            });
            for (var N in G) {
                if (typeof G[N] !== "function") {
                    G[N].front.find("img").attr("src", s.get(M).src);
                    G[N].back.find("img").attr("src", s.get(X).src)
                }
            }
            if (!x[M]) {
                x[M] = C(M)
            }
            d = new k(G, M, K, function() {
                u.show();
                n.trigger("effectEnd");
                o.hide();
                for (var i in G) {
                    if (typeof G[i] !== "function") {
                        G[i].part.css({
                            transition: "",
                            transform: "rotateX(0) rotateY(0) translate3d(0,0,0)"
                        })
                    }
                }
                d = 0
            })
        } else {
            d = true;

            function Y(j, i) {
                return Math.random() * (i - j + 1) + j
            }
            var T = g.width(),
                W = g.height(),
                S = T / a,
                V = W / r,
                L = T - S * (a - 1),
                U = W - V * (r - 1);
            o.css({
                width: T,
                height: W
            });
            var J = 0;
            for (var N in G) {
                var R = N % a,
                    P = Math.floor(N / a);
                G[N].front.find("img").attr("src", s.get(X).src).css(K);
                var Z = f.duration * (1 - Math.abs((c * H - R * P) / (2 * r * a)));
                var Q = Y(-1, 1) > 0 ? 1 : -1;
                var O = Y(-1, 1) > 0 ? 1 : -1;
                G[N].wrapper.css({
                    width: S,
                    height: V
                });
                G[N].part.css({
                    position: "absolute",
                    top: Q * V,
                    left: O * S,
                    opacity: 0,
                    width: S,
                    height: V
                }).animate({
                    top: 0,
                    left: 0,
                    opacity: 1
                }, Z, function() {
                    J++;
                    if (J == r * a) {
                        u.stop(1, 1);
                        d = false;
                        n.trigger("effectEnd")
                    }
                })
            }
        }
    };

    function F(S, J) {
        J = J || {};
        var U = 1,
            M = J.exclude || [],
            R;
        var O = document.createElement("canvas"),
            L = O.getContext("2d"),
            K = O.width = S.naturalWidth,
            Y = O.height = S.naturalHeight;
        L.drawImage(S, 0, 0, S.naturalWidth, S.naturalHeight);
        try {
            R = L.getImageData(J.x ? J.x : 0, J.y ? J.y : 0, J.w ? J.w : S.width, J.h ? J.h : S.height)["data"]
        } catch (T) {
            console.log("error:unable to access image data: " + T);
            return "#ccc"
        }
        var N = (J.w ? J.w : S.width * J.h ? J.h : S.height) || R.length,
            P = {},
            W = "",
            V = [],
            j = {
                dominant: {
                    name: "",
                    count: 0
                }
            };
        var Q = 0;
        while (Q < N) {
            V[0] = R[Q];
            V[1] = R[Q + 1];
            V[2] = R[Q + 2];
            W = V.join(",");
            if (W in P) {
                P[W] = P[W] + 1
            } else {
                P[W] = 1
            }
            if (M.indexOf(["rgb(", W, ")"].join("")) === -1) {
                var X = P[W];
                if (X > j.dominant.count) {
                    j.dominant.name = W;
                    j.dominant.count = X
                }
            }
            Q += U * 4
        }
        return ["rgb(", j.dominant.name, ")"].join("")
    }
}; // -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_kenburns(d, l, m) {
    var e = jQuery;
    var g = e(this);
    var f = document.createElement("canvas").getContext;
    var i = e("<div>").css({
        position: "absolute",
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
        overflow: "hidden"
    }).addClass("ws_effect ws_kenburns").appendTo(m);
    var o = d.paths || [{
        from: [0, 0, 1],
        to: [0, 0, 1.2]
    }, {
        from: [0, 0, 1.2],
        to: [0, 0, 1]
    }, {
        from: [1, 0, 1],
        to: [1, 0, 1.2]
    }, {
        from: [0, 1, 1.2],
        to: [0, 1, 1]
    }, {
        from: [1, 1, 1],
        to: [1, 1, 1.2]
    }, {
        from: [0.5, 1, 1],
        to: [0.5, 1, 1.3]
    }, {
        from: [1, 0.5, 1.2],
        to: [1, 0.5, 1]
    }, {
        from: [1, 0.5, 1],
        to: [1, 0.5, 1.2]
    }, {
        from: [0, 0.5, 1.2],
        to: [0, 0.5, 1]
    }, {
        from: [1, 0.5, 1.2],
        to: [1, 0.5, 1]
    }, {
        from: [0.5, 0.5, 1],
        to: [0.5, 0.5, 1.2]
    }, {
        from: [0.5, 0.5, 1.3],
        to: [0.5, 0.5, 1]
    }, {
        from: [0.5, 1, 1],
        to: [0.5, 0, 1.15]
    }];

    function c(h) {
        return o[h ? Math.floor(Math.random() * (f ? o.length : Math.min(5, o.length))) : 0]
    }
    var k = d.width,
        p = d.height;
    var j, b;
    var a, r;

    function n() {
        a = e('<div style="width:100%;height:100%"></div>').css({
            "z-index": 8,
            position: "absolute",
            left: 0,
            top: 0
        }).appendTo(i)
    }
    n();

    function s(w, t, h) {
        var u = {
            width: 100 * w[2] + "%"
        };
        u[t ? "right" : "left"] = -100 * (w[2] - 1) * (t ? (1 - w[0]) : w[0]) + "%";
        u[h ? "bottom" : "top"] = -100 * (w[2] - 1) * (h ? (1 - w[1]) : w[1]) + "%";
        if (!f) {
            for (var v in u) {
                if (/\%/.test(u[v])) {
                    u[v] = (/right|left|width/.test(v) ? k : p) * parseFloat(u[v]) / 100 + "px"
                }
            }
        }
        return u
    }

    function q(w, z, A) {
        var t = e(w);
        t = {
            width: t.width(),
            height: t.height(),
            marginTop: t.css("marginTop"),
            marginLeft: t.css("marginLeft")
        };
        if (f) {
            if (b) {
                b.stop(1)
            }
            b = j
        }
        if (r) {
            r.remove()
        }
        r = a;
        n();
        if (A) {
            a.hide();
            r.stop(true, true)
        }
        if (f) {
            var y, x;
            var u, h;
            u = e('<canvas width="' + k + '" height="' + p + '"/>');
            u.css({
                position: "absolute",
                left: 0,
                top: 0
            }).css(t).appendTo(a);
            y = u.get(0).getContext("2d");
            h = u.clone().appendTo(a);
            x = h.get(0).getContext("2d");
            j = wowAnimate(function(B) {
                var D = [z.from[0] * (1 - B) + B * z.to[0], z.from[1] * (1 - B) + B * z.to[1], z.from[2] * (1 - B) + B * z.to[2]];
                x.drawImage(w, -k * (D[2] - 1) * D[0], -p * (D[2] - 1) * D[1], k * D[2], p * D[2]);
                y.clearRect(0, 0, k, p);
                var C = y;
                y = x;
                x = C
            }, 0, 1, d.duration + d.delay * 2)
        } else {
            k = t.width;
            p = t.height;
            var v = e('<img src="' + w.src + '"/>').css({
                position: "absolute",
                left: "auto",
                right: "auto",
                top: "auto",
                bottom: "auto"
            }).appendTo(a).css(s(z.from, z.from[0] > 0.5, z.from[1] > 0.5)).animate(s(z.to, z.from[0] > 0.5, z.from[1] > 0.5), {
                easing: "linear",
                queue: false,
                duration: (1.5 * d.duration + d.delay)
            })
        }
        if (A) {
            a.fadeIn(d.duration)
        }
    }
    if (d.effect.length == 1) {
        e(function() {
            l.each(function(h) {
                e(this).css({
                    visibility: "hidden"
                });
                if (h == d.startSlide) {
                    q(this, c(h), 0)
                }
            })
        })
    }
    this.go = function(h, t) {
        setTimeout(function() {
            g.trigger("effectEnd")
        }, d.duration);
        q(l.get(h), c(h), 1)
    }
}; // -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_book(p, n, b) {
    var f = jQuery;
    var m = f(this);
    var i = f(".ws_list", b);
    var k = f("<div>").addClass("ws_effect ws_book").css({
            position: "absolute",
            top: 0,
            left: 0,
            width: "100%",
            height: "100%"
        }).appendTo(b),
        e = p.duration,
        d = p.perspective || 0.4,
        g = p.shadow || 0.35,
        a = p.noCanvas || false,
        l = p.no3d || false;
    var o = {
        domPrefixes: " Webkit Moz ms O Khtml".split(" "),
        testDom: function(r) {
            var q = this.domPrefixes.length;
            while (q--) {
                if (typeof document.body.style[this.domPrefixes[q] + r] !== "undefined") {
                    return true
                }
            }
            return false
        },
        cssTransitions: function() {
            return this.testDom("Transition")
        },
        cssTransforms3d: function() {
            var r = (typeof document.body.style.perspectiveProperty !== "undefined") || this.testDom("Perspective");
            if (r && /AppleWebKit/.test(navigator.userAgent)) {
                var t = document.createElement("div"),
                    q = document.createElement("style"),
                    s = "Test3d" + Math.round(Math.random() * 99999);
                q.textContent = "@media (-webkit-transform-3d){#" + s + "{height:3px}}";
                document.getElementsByTagName("head")[0].appendChild(q);
                t.id = s;
                document.body.appendChild(t);
                r = t.offsetHeight === 3;
                q.parentNode.removeChild(q);
                t.parentNode.removeChild(t)
            }
            return r
        },
        canvas: function() {
            if (typeof document.createElement("canvas").getContext !== "undefined") {
                return true
            }
        }
    };
    if (!l) {
        l = o.cssTransitions() && o.cssTransforms3d()
    }
    if (!a) {
        a = o.canvas()
    }
    var j;
    this.go = function(r, q, E) {
        if (j) {
            return -1
        }
        var v = n.get(r),
            G = n.get(q);
        if (E == undefined) {
            E = (q == 0 && r != q + 1) || (r == q - 1)
        } else {
            E = !E
        }
        var s = f("<div>").appendTo(k);
        var t = f(v);
        t = {
            width: t.width(),
            height: t.height(),
            marginLeft: parseFloat(t.css("marginLeft")),
            marginTop: parseFloat(t.css("marginTop"))
        };
        if (l) {
            var y = {
                background: "#000",
                position: "absolute",
                left: 0,
                top: 0,
                width: "100%",
                height: "100%",
                transformStyle: "preserve-3d",
                zIndex: 3,
                outline: "1px solid transparent"
            };
            perspect = b.width() * (3 - d * 2);
            s.css(y).css({
                perspective: perspect,
                transform: "translate3d(0,0,0)"
            });
            var z = 90;
            var D = f("<div>").css(y).css({
                position: "relative",
                "float": "left",
                width: "50%",
                overflow: "hidden"
            }).append(f("<img>").attr("src", (E ? v : G).src).css(t)).appendTo(s);
            var C = f("<div>").css(y).css({
                position: "relative",
                "float": "left",
                width: "50%",
                overflow: "hidden"
            }).append(f("<img>").attr("src", (E ? G : v).src).css(t).css({
                marginLeft: -t.width / 2
            })).appendTo(s);
            var I = f("<div>").css(y).css({
                display: E ? "block" : "none",
                width: "50%",
                transform: "rotateY(" + (E ? 0.1 : z) + "deg)",
                transition: (E ? "ease-in " : "ease-out ") + e / 2000 + "s",
                transformOrigin: "right",
                overflow: "hidden"
            }).append(f("<img>").attr("src", (E ? G : v).src).css(t)).appendTo(s);
            var F = f("<div>").css(y).css({
                display: E ? "none" : "block",
                left: "50%",
                width: "50%",
                transform: "rotateY(-" + (E ? z : 0.1) + "deg)",
                transition: (E ? "ease-out " : "ease-in ") + e / 2000 + "s",
                transformOrigin: "left",
                overflow: "hidden"
            }).append(f("<img>").attr("src", (E ? v : G).src).css(t).css({
                marginLeft: -t.width / 2
            })).appendTo(s)
        } else {
            if (a) {
                var x = f("<div>").css({
                    position: "absolute",
                    top: 0,
                    left: E ? 0 : "50%",
                    width: "50%",
                    height: "100%",
                    overflow: "hidden",
                    zIndex: 6
                }).append(f(n.get(r)).clone().css({
                    position: "absolute",
                    height: "100%",
                    right: E ? "auto" : 0,
                    left: E ? 0 : "auto"
                })).appendTo(s).hide();
                var B = f("<div>").css({
                    position: "absolute",
                    width: "100%",
                    height: "100%",
                    left: 0,
                    top: 0,
                    zIndex: 8
                }).appendTo(s).hide();
                var H = f("<canvas>").css({
                    position: "absolute",
                    zIndex: 2,
                    left: 0,
                    top: -B.height() * d / 2
                }).attr({
                    width: B.width(),
                    height: B.height() * (d + 1)
                }).appendTo(B);
                var A = H.clone().css({
                    top: 0,
                    zIndex: 1
                }).attr({
                    width: B.width(),
                    height: B.height()
                }).appendTo(B);
                var w = H.get(0).getContext("2d");
                var u = A.get(0).getContext("2d")
            } else {
                i.stop(true).animate({
                    left: (r ? -r + "00%" : (/Safari/.test(navigator.userAgent) ? "0%" : 0))
                }, e, "easeInOutExpo")
            }
        }
        if (!l && a) {
            var D = w;
            var C = u;
            var I = G;
            var F = v
        }
        j = new h(E, z, D, C, I, F, B, H, A, x, t, function() {
            m.trigger("effectEnd");
            s.remove();
            j = 0
        })
    };

    function c(G, s, A, v, u, E, D, C, B, t, r) {
        numSlices = u / 2, widthScale = u / B, heightScale = (1 - E) / numSlices;
        G.clearRect(0, 0, r.width(), r.height());
        for (var q = 0; q < numSlices + widthScale; q++) {
            var z = (D ? q * p.width / u + p.width / 2 : (numSlices - q) * p.width / u);
            var H = A + (D ? 2 : -2) * q,
                F = v + t * heightScale * q / 2;
            if (z < 0) {
                z = 0
            }
            if (H < 0) {
                H = 0
            }
            if (F < 0) {
                F = 0
            }
            G.drawImage(s, z, 0, 2.5, p.height, H, F, 2, t * (1 - (heightScale * q)))
        }
        G.save();
        G.beginPath();
        G.moveTo(A, v);
        G.lineTo(A + (D ? 2 : -2) * (numSlices + widthScale), v + t * heightScale * (numSlices + widthScale) / 2);
        G.lineTo(A + (D ? 2 : -2) * (numSlices + widthScale), t * (1 - heightScale * (numSlices + widthScale)) + v + t * heightScale * (numSlices + widthScale) / 2);
        G.lineTo(A, v + t);
        G.closePath();
        G.clip();
        G.fillStyle = "rgba(0,0,0," + Math.round(C * 100) / 100 + ")";
        G.fillRect(0, 0, r.width(), r.height());
        G.restore()
    }

    function h(A, r, C, B, y, x, v, w, u, z, t, E) {
        if (l) {
            if (!A) {
                r *= -1;
                var D = B;
                B = C;
                C = D;
                D = x;
                x = y;
                y = D
            }
            setTimeout(function() {
                C.children("img").css("opacity", g).animate({
                    opacity: 1
                }, e / 2);
                y.css("transform", "rotateY(" + r + "deg)").children("img").css("opacity", 1).animate({
                    opacity: g
                }, e / 2, function() {
                    y.hide();
                    x.show().css("transform", "rotateX(0deg) rotateY(0deg)").children("img").css("opacity", g).animate({
                        opacity: 1
                    }, e / 2);
                    B.children("img").css("opacity", 1).animate({
                        opacity: g
                    }, e / 2)
                })
            }, 0);
            setTimeout(E, e)
        } else {
            if (a) {
                v.show();
                var q = new Date;
                var s = true;
                wowAnimate(function(F) {
                    var I = jQuery.easing.easeInOutQuint(1, F, 0, 1, 1),
                        H = jQuery.easing.easeInOutCubic(1, F, 0, 1, 1),
                        L = !A;
                    if (F < 0.5) {
                        I *= 2;
                        H *= 2;
                        var G = y
                    } else {
                        L = A;
                        I = (1 - I) * 2;
                        H = (1 - H) * 2;
                        var G = x
                    }
                    var J = v.height() * d / 2,
                        N = (1 - I) * v.width() / 2,
                        M = 1 + H * d,
                        K = v.width() / 2;
                    c(C, G, K, J, N, M, L, H * g, K, v.height(), w);
                    if (s) {
                        z.show();
                        s = false
                    }
                    B.clearRect(0, 0, u.width(), u.height());
                    B.fillStyle = "rgba(0,0,0," + (g - H * g) + ")";
                    B.fillRect(L ? K : 0, 0, u.width() / 2, u.height())
                }, 0, 1, e, E)
            }
        }
    }
}
jQuery.extend(jQuery.easing, {
    easeInOutCubic: function(e, f, a, h, g) {
        if ((f /= g / 2) < 1) {
            return h / 2 * f * f * f + a
        }
        return h / 2 * ((f -= 2) * f * f + 2) + a
    },
    easeInOutQuint: function(e, f, a, h, g) {
        if ((f /= g / 2) < 1) {
            return h / 2 * f * f * f * f * f + a
        }
        return h / 2 * ((f -= 2) * f * f * f * f + 2) + a
    }
}); // -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_slices(k, h, i) {
    var b = jQuery;
    var f = b(this);

    function g(q, p, o, m, l, n) {
        if (k.support.transform) {
            if (p.top) {
                p.translate = [0, p.top || 0, 0]
            }
            if (o.top) {
                o.translate = [0, o.top || 0, 0]
            }
            delete p.top;
            delete o.top
        }
        wowAnimate(q, p, o, m, l, "swing", n)
    }
    var e = function(r, x) {
        var q = b.extend({}, {
            effect: "random",
            slices: 15,
            animSpeed: 500,
            pauseTime: 3000,
            startSlide: 0,
            container: null,
            onEffectEnd: 0
        }, x);
        var t = {
            currentSlide: 0,
            currentImage: "",
            totalSlides: 0,
            randAnim: "",
            stop: false
        };
        var o = b(r);
        o.data("wow:vars", t);
        if (!/absolute|relative/.test(o.css("position"))) {
            o.css("position", "relative")
        }
        var m = x.container || o;
        var p = o.children();
        t.totalSlides = p.length;
        if (q.startSlide > 0) {
            if (q.startSlide >= t.totalSlides) {
                q.startSlide = t.totalSlides - 1
            }
            t.currentSlide = q.startSlide
        }
        if (b(p[t.currentSlide]).is("img")) {
            t.currentImage = b(p[t.currentSlide])
        } else {
            t.currentImage = b(p[t.currentSlide]).find("img:first")
        }
        if (b(p[t.currentSlide]).is("a")) {
            b(p[t.currentSlide]).css("display", "block")
        }
        for (var s = 0; s < q.slices; s++) {
            var w = Math.round(m.width() / q.slices);
            var v = b('<div class="wow-slice"></div>').css({
                left: w * s + "px",
                overflow: "hidden",
                width: ((s == q.slices - 1) ? (m.width() - (w * s)) : w) + "px",
                position: "absolute"
            }).appendTo(m);
            b("<img>").css({
                position: "absolute",
                left: 0,
                top: 0,
                transform: "translate3d(0,0,0)"
            }).appendTo(v)
        }
        var n = 0;
        this.sliderRun = function(y, z) {
            if (t.busy) {
                return false
            }
            q.effect = z || q.effect;
            t.currentSlide = y - 1;
            u(o, p, q, false);
            return true
        };
        var l = function() {
            if (q.onEffectEnd) {
                q.onEffectEnd(t.currentSlide)
            }
            m.hide();
            b(".wow-slice", m).css({
                transition: "",
                transform: ""
            });
            t.busy = 0
        };
        var u = function(y, z, C, E) {
            var F = y.data("wow:vars");
            if ((!F || F.stop) && !E) {
                return false
            }
            F.busy = 1;
            F.currentSlide++;
            if (F.currentSlide == F.totalSlides) {
                F.currentSlide = 0
            }
            if (F.currentSlide < 0) {
                F.currentSlide = (F.totalSlides - 1)
            }
            F.currentImage = b(z[F.currentSlide]);
            if (!F.currentImage.is("img")) {
                F.currentImage = F.currentImage.find("img:first")
            }
            var A = b(h[F.currentSlide]);
            A = {
                width: A.width(),
                heiht: A.height(),
                marginTop: A.css("marginTop"),
                marginLeft: A.css("marginLeft")
            };
            b(".wow-slice", m).each(function(J) {
                var L = b(this),
                    I = b("img", L);
                var K = Math.round(m.width() / C.slices);
                I.width(m.width());
                I.attr("src", F.currentImage.attr("src"));
                I.css({
                    left: -K * J + "px"
                }).css(A);
                L.css({
                    height: "100%",
                    opacity: 0,
                    left: K * J,
                    width: ((J == C.slices - 1) ? (m.width() - (K * J)) : K)
                })
            });
            m.show();
            if (C.effect == "random") {
                var G = new Array("sliceDownRight", "sliceDownLeft", "sliceUpRight", "sliceUpLeft", "sliceUpDownRight", "sliceUpDownLeft", "fold", "fade");
                F.randAnim = G[Math.floor(Math.random() * (G.length + 1))];
                if (F.randAnim == undefined) {
                    F.randAnim = "fade"
                }
            }
            if (C.effect.indexOf(",") != -1) {
                var G = C.effect.split(",");
                F.randAnim = b.trim(G[Math.floor(Math.random() * G.length)])
            }
            if (C.effect == "sliceDown" || C.effect == "sliceDownRight" || F.randAnim == "sliceDownRight" || C.effect == "sliceDownLeft" || F.randAnim == "sliceDownLeft") {
                var B = 0;
                var H = b(".wow-slice", m);
                if (C.effect == "sliceDownLeft" || F.randAnim == "sliceDownLeft") {
                    H = H._reverse()
                }
                H.each(function(I) {
                    g(b(this), {
                        top: "-100%",
                        opacity: 0
                    }, {
                        top: "0%",
                        opacity: 1
                    }, C.animSpeed, 100 + B, (I == C.slices - 1) ? l : 0);
                    B += 50
                })
            } else {
                if (C.effect == "sliceUp" || C.effect == "sliceUpRight" || F.randAnim == "sliceUpRight" || C.effect == "sliceUpLeft" || F.randAnim == "sliceUpLeft") {
                    var B = 0;
                    var H = b(".wow-slice", m);
                    if (C.effect == "sliceUpLeft" || F.randAnim == "sliceUpLeft") {
                        H = H._reverse()
                    }
                    H.each(function(I) {
                        g(b(this), {
                            top: "100%",
                            opacity: 0
                        }, {
                            top: "0%",
                            opacity: 1
                        }, C.animSpeed, 100 + B, (I == C.slices - 1) ? l : 0);
                        B += 50
                    })
                } else {
                    if (C.effect == "sliceUpDown" || C.effect == "sliceUpDownRight" || F.randAnim == "sliceUpDownRight" || C.effect == "sliceUpDownLeft" || F.randAnim == "sliceUpDownLeft") {
                        var B = 0;
                        var H = b(".wow-slice", m);
                        if (C.effect == "sliceUpDownLeft" || F.randAnim == "sliceUpDownLeft") {
                            H = H._reverse()
                        }
                        H.each(function(I) {
                            g(b(this), {
                                top: ((I % 2) ? "-" : "") + "100%",
                                opacity: 0
                            }, {
                                top: "0%",
                                opacity: 1
                            }, C.animSpeed, 100 + B, (I == C.slices - 1) ? l : 0);
                            B += 50
                        })
                    } else {
                        if (C.effect == "fold" || F.randAnim == "fold") {
                            var B = 0;
                            var H = b(".wow-slice", m);
                            var D = H.width();
                            H.each(function(I) {
                                g(b(this), {
                                    width: 0,
                                    opacity: 0
                                }, {
                                    width: D,
                                    opacity: 1
                                }, C.animSpeed, 100 + B, (I == C.slices - 1) ? l : 0);
                                B += 50
                            })
                        } else {
                            if (C.effect == "fade" || F.randAnim == "fade") {
                                var H = b(".wow-slice", m);
                                b(".wow-slice", m).each(function(I) {
                                    b(this).css("height", "100%");
                                    b(this).animate({
                                        opacity: "1.0"
                                    }, (C.animSpeed * 2), (I == C.slices - 1) ? l : 0)
                                })
                            }
                        }
                    }
                }
            }
        }
    };
    b.fn._reverse = [].reverse;
    var a = b("li", i);
    var c = b("ul", i);
    var d = b("<div>").addClass("ws_effect ws_slices").css({
        left: 0,
        top: 0,
        "z-index": 8,
        overflow: "hidden",
        width: "100%",
        height: "100%",
        position: "absolute"
    }).appendTo(i);
    var j = new e(c, {
        keyboardNav: false,
        caption: 0,
        effect: "sliceDownRight,sliceDownLeft,sliceUpRight,sliceUpLeft,sliceUpDownRight,sliceUpDownLeft,sliceUpDownRight,sliceUpDownLeft,fold,fold,fold",
        animSpeed: k.duration,
        startSlide: k.startSlide,
        container: d,
        onEffectEnd: function(l) {
            f.trigger("effectEnd")
        }
    });
    this.go = function(m, l) {
        var n = j.sliderRun(m);
        if (k.fadeOut) {
            c.fadeOut(k.duration)
        }
    }
}; // -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_blinds(m, l, a) {
    var g = jQuery;
    var k = g(this);
    var c = m.parts || 3;
    var j = g(".ws_list", a);
    var h = g("<div>").addClass("ws_effect ws_blinds").css({
        position: "absolute",
        width: "100%",
        height: "100%",
        left: 0,
        top: 0,
        "z-index": 8
    }).hide().appendTo(a);
    var d = g("<div>").css({
        position: "absolute",
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
        overflow: "hidden"
    }).appendTo(h);
    var e = [];
    var b = document.addEventListener;
    for (var f = 0; f < c; f++) {
        e[f] = g("<div>").css({
            position: b ? "relative" : "absolute",
            display: b ? "inline-block" : "block",
            height: "100%",
            width: (100 / c + 0.001).toFixed(3) + "%",
            border: "none",
            margin: 0,
            overflow: "hidden",
            top: 0,
            left: b ? 0 : ((100 * f / c).toFixed(3) + "%")
        }).appendTo(h)
    }
    this.go = function(r, p, o) {
        if (o == undefined) {
            o = p > r ? 1 : 0
        }
        h.find("img").stop(true, true);
        h.show();
        var s = g(l[p]);
        var t = {
            width: s.width() || m.width,
            height: s.height() || m.height
        };
        var u = s.clone().css(t).appendTo(d);
        u.from = {
            left: 0
        };
        u.to = {
            left: (!o ? 1 : -1) * u.width() * 0.5
        };
        if (m.support.transform) {
            u.from = {
                translate: [u.from.left, 0, 0]
            };
            u.to = {
                translate: [u.to.left, 0, 0]
            }
        }
        j.hide();
        wowAnimate(u, u.from, u.to, m.duration, m.duration * 0.1, "swing");
        for (var q = 0; q < e.length; q++) {
            var n = e[q];
            var v = g(l[r]).clone().css({
                position: "absolute",
                top: 0
            }).css(t).appendTo(n);
            v.from = {
                left: (!o ? -1 : 1) * v.width() - n.position().left
            };
            v.to = {
                left: -n.position().left
            };
            if (m.support.transform) {
                v.from = {
                    translate: [v.from.left, 0, 0]
                };
                v.to = {
                    translate: [v.to.left, 0, 0]
                }
            }
            wowAnimate(v, v.from, v.to, (m.duration / (e.length + 1)) * (o ? (e.length - q + 1) : (q + 2)), "swing", ((!o && q == e.length - 1 || o && !q) ? function() {
                k.trigger("effectEnd");
                h.hide().find("img").remove();
                u.remove()
            } : false))
        }
    }
}; // -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({
    effect: "parallax,brick,kenburns,book,slices,blinds",
    prev: "",
    next: "",
    duration: 20 * 100,
    delay: 20 * 100,
    width: 1024,
    height: 768,
    autoPlay: true,
    autoPlayVideo: false,
    playPause: false,
    stopOnHover: false,
    loop: false,
    bullets: 0,
    caption: false,
    captionEffect: "parallax",
    controls: false,
    controlsThumb: false,
    responsive: 3,
    fullScreen: false,
    gestures: 2,
    onBeforeStep: 0,
    images: 0
});